version: "2"

networks:
  workshop-network:
     driver: bridge

volumes:
    jenkins-volume:

services:
    jenkins:
        container_name: jenkins
        build: jenkins
        ports: 
            - 8081:8080
            - 50000:50000
        volumes: 
            - jenkins-volume:/var/
            - /var/run/docker.sock:/var/run/docker.sock 
            - $(which docker):/usr/bin/docker
        networks:
            - workshop-network
    database:
        container_name: database
        build: database
        ports:
            - 5432:5432
        networks:
            - workshop-network
    glassfish:
        container_name: glassfish
        image: payara/server-full
        ports:
            - 8080:8080
            - 4848:4848
        networks:
            - workshop-network
    sonarqube:
        container_name: sonarqube
        image: sonarqube
        ports:
            - 9000:9000
        networks:
            - workshop-network
    