version: "2"

networks:
  workshop-network:
     driver: bridge

volumes:
    jenkins-volume:

services:
    jenkins:
        container_name: jenkins
        build: jenkins
        ports: 
            - 8081:8080
            - 50000:50000
        volumes: 
            - jenkins-volume:/var/
            - /var/run/docker.sock:/var/run/docker.sock 
            - /usr/bin/docker:/usr/bin/docker
        networks:
            - workshop-network
